---
# this file contains properties for the prod environment that are not sensitive
# for the prod environment, sensitive properties are found in the Ansible Tower test inventory
installer_user: "ubuntu"
services_host: "34.195.196.20"
use_secure_http: true
use_custom_ssl_certificates: true
custom_ssl_certificates_path: "/home/ubuntu/certificates"
aws_output_format: "json"
mysql_host: "localhost"
email_account_description: "SMART Account Services"
email_smtp_port: "587"
email_admin_address: "travis@isalussolutions.com"
email_contact_addresss: "support@smarthealthit.org"
apacheds_server_external_host: "sb-ldap.smarthealthit.org"
apacheds_server_installer_enabled: true
pwm_server_external_host: "sb-pwm.smarthealthit.org"
pwm_server_external_port: "443"
pwm_unlocked: false
pwm_sso_authentication_header_name: "c8381465-a7f8-4ecc-958d-ec296d6e8671"
account_server_external_url: "{{pwm_server_external_url}}"
auth_server_external_host: "sb-auth.smarthealthit.org"
auth_server_external_port: "443"
auth_server_artifact_version: "1.9.9"
auth_server_initial_memory: "32M"
auth_server_max_memory: "512M"
auth_server_newUserUrl: "{{pwm_server_external_url}}public/newuser"
auth_server_forgotPasswordUrl: "{{pwm_server_external_url}}public/forgottenpassword"
auth_mysql_reset_database: false
api_server_oauth2_clientId: "hspc_resource_server"
enable_monitoring: true
enable_backup_restore_jobs: true
enable_aws_snapshot: true
enable_pwm: true
enable_api_sample_data: false
enable_mock_endpoints: true
api_dstu2_server_external_host: "sb-fhir-dstu2.smarthealthit.org"
api_dstu2_server_external_port: "443"
api_dstu2_server_initial_memory: "256M"
api_dstu2_server_max_memory: "512M"
api_dstu2_mysql_reset_database: false
api_dstu2_sample_patients_limit: "9999"
mock_api_dstu2_server_external_host: "sb-mock-fhir-dstu2.smarthealthit.org"
mock_api_dstu2_server_external_port: "443"
mock_api_dstu2_server_initial_memory: "256M"
mock_api_dstu2_server_max_memory: "512M"
api_stu3_server_external_host: "sb-fhir-stu3.smarthealthit.org"
api_stu3_server_external_port: "443"
api_stu3_server_initial_memory: "256M"
api_stu3_server_max_memory: "512M"
api_stu3_mysql_reset_database: false
api_stu3_sample_patients_limit: "9999"
mock_api_stu3_server_external_host: "sb-mock-fhir-stu3.smarthealthit.org"
mock_api_stu3_server_external_port: "443"
mock_api_stu3_server_initial_memory: "256M"
mock_api_stu3_server_max_memory: "512M"
messaging_server_external_host: "localhost"
messaging_server_external_port: "8091"
messaging_server_initial_memory: "32M"
messaging_server_max_memory: "64M"
messaging_profiles: "production"
sandman_server_project_version: "2.6.7"
sandman_server_external_host: "sandbox.smarthealthit.org"
sandman_server_external_port: "443"
sandman_server_api_v1_url: "{{api_dstu2_server_external_url}}"
sandman_server_api_v2_url: "{{api_stu3_server_external_url}}"
sandman_api_server_artifact_repository_url: "{{release_repository_url}}"
sandman_api_server_artifact_version: "0.5.12"
sandman_api_server_external_host: "sb-api.smarthealthit.org"
sandman_api_server_external_port: "443"
sandman_api_server_initial_memory: "128M"
sandman_api_server_max_memory: "256M"
sandman_api_server_send_email: false
sandman_api_mysql_database_drop: false
sandman_api_server_api_v1_url: "{{api_dstu2_server_external_url}}"
sandman_api_server_api_v2_url: "{{api_stu3_server_external_url}}"
sandman_api_server_api_v3_url: "{{api_stu3_server_external_url}}"
sandman_api_server_api_v4_url: "{{api_stu3_server_external_url}}"
sandman_api_server_default_system_roles: "USER"
apps_server_external_host: "sb-apps.smarthealthit.org"
apps_server_external_port: "443"
patient_picker_server_external_host: "{{apps_server_external_host}}"
patient_picker_server_external_port: "{{apps_server_external_port}}"
patient_data_manager_project_version: "1.0.2"
patient_data_manager_server_external_host: "{{services_host}}"
patient_data_manager_server_external_port: "9096"
bilirubin_risk_chart_project_version: "master"
bilirubin_risk_chart_server_external_host: "{{services_host}}"
bilirubin_risk_chart_server_external_port: "9086"
