---
- name: configure api-dstu2-server service
  tags: [api-dstu2-all, api-dstu2-server, smart-platform]
  template: src=api-dstu2-server.service.j2
            dest=/etc/systemd/system/api-dstu2-server.service
            owner=root group=root mode=0644

- name: enable api-dstu2-server service
  tags: [api-dstu2-all, api-dstu2-server, smart-platform]
  shell: systemctl enable api-dstu2-server.service

- name: reload systemd daemon
  tags: [api-dstu2-all, api-dstu2-server, smart-platform]
  shell: systemctl daemon-reload

- name: stop api-dstu2-server
  tags: [api-dstu2-all, api-dstu2-server, smart-platform]
  service: name=api-dstu2-server state=stopped

- name: configure nginx (api-dstu2-server)
  tags: [api-dstu2-all, api-dstu2-server, smart-platform]
  template: src=nginx_api_dstu2.j2 dest=/etc/nginx/sites-enabled/api_dstu2 owner=root group=root mode=0644
  notify:
    - restart nginx

- meta: flush_handlers

- name: restart api-dstu2-server
  tags: [api-dstu2-all, api-dstu2-server, smart-platform]
  service: name=api-dstu2-server enabled=yes state=restarted

- name: verify api-dstu2-server is available
  tags: [api-dstu2-all, api-dstu2-server, verify, smart-platform]
  wait_for: host={{api_dstu2_server_internal_host}} port={{api_dstu2_server_internal_port}}
